responses = {
    "Positive": [
        "That's great to hear!",
        "I'm glad you're having a good day.",
        "That's fantastic news!",
        "I'm so happy for you!",
        "That's wonderful!",
        "That's so cool!",
        "That's great to hear!",
        "I'm thrilled for you!",
        "That's excellent!",
        "That's amazing!",
    ],
    "Negative": [
        "I'm sorry to hear that.",
        "That sounds really tough.",
        "I'm here to help if you need to talk.",
        "I hope things get better soon.",
        "That's too bad.",
        "I'm sorry to hear that you're feeling that way.",
        "I'm here to listen.",
        "I hope things improve for you.",
        "That's unfortunate.",
        "I'm sorry for your loss.",
    ],
    "Neutral": [
        "Interesting.",
        "I see.",
        "Okay.",
        "Got it.",
        "Sure thing.",
        "Alright.",
        "Noted.",
        "Understood.",
        "I hear you.",
        "I see what you mean.",
    ],
}